version: "3.8"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1235*
      MYSQL_DATABASE: filip
      MYSQL_USER: admin

      #Keep this same as root password
      MYSQL_PASSWORD: root1235*
    ports:
      - "3306:3306"
    volumes:
      - db_filip_data:/var/lib/mysql

  #So you can view database in web gui
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root1235*
    ports:
      - "8090:80"

volumes:
  db_filip_data:
